
tests-run:
  image: $DOCKERFILE_RUNNER_VERSION
  stage: test
  when: manual
  services:
    - docker:dind
  variables:
    DOCKER_HOST: tcp://docker:2375/
  before_script:
    - mkdir $DOWNLOADS_FOLDER
    - chmod a+w $DOWNLOADS_FOLDER
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
    - docker network create selenium-grid-network
    - docker-compose up --scale selenium-$BROWSER=$THREADS -d
  script:
    - chmod +x gradlew
    - docker ps
    - ./gradlew -DuseGrid=true -Dbrowser=$BROWSER -Dthreads=$THREADS -DincludeTags=$TAG -Ddownloads=$DOWNLOADS_FOLDER clean test allureReport
  after_script:
    - docker ps -a
    - docker logs selenium-hub
#    - docker logs selenium_hub_cicd-selenium-firefox-1 || true #useful for debugging issues with containers
    - for i in $(seq 1 $THREADS); do echo -e "#######################"; echo $CI_PROJECT_NAME-selenium-$BROWSER-$i; docker logs $CI_PROJECT_NAME-selenium-$BROWSER-$i; done
    - docker-compose down
    - ls -al build
    - ls -al build/reports
    - ls -al build/reports/allure-report/
    - ls -al build/reports/allure-report/allureReport/
    - ls -a $DOWNLOADS_FOLDER
    - mkdir public
    - mkdir public/Downloads
    - mkdir public/allureReport
    - mv build/reports/allure-report/allureReport/* public/allureReport
    - mv $DOWNLOADS_FOLDER/* public/Downloads

  artifacts:
    paths:
      - public
    expire_in: 3 days
