variables:
  DOCKERFILE_RUNNER_VERSION: $CI_REGISTRY_IMAGE/runner:1.0
  DOCKERFILE_HUB_VERSION: $CI_REGISTRY_IMAGE/hub:4.23.1
  DOCKERFILE_CHROME_VERSION: $CI_REGISTRY_IMAGE/chrome:127.0
  DOCKERFILE_FIREFOX_VERSION: $CI_REGISTRY_IMAGE/firefox:129.0
  DOCKERFILE_EDGE_VERSION: $CI_REGISTRY_IMAGE/edge:127.0
  DOWNLOADS_FOLDER: ./Downloads
  THREADS:
    value: 2
    description: "Number of threads to run tests. "
  TAG:
    value: "regression"
    description: "Tags which define the scope of the run. Like 'regression'"
  BROWSER:
    value: "firefox"
    description: "Browser to use: 'chrome', 'edge' or 'firefox'"

stages:
  - build
  - test

include:
  - local: '.gitlab-ci-docker.yml'
  - local: '.gitlab-ci-test.yml'