services:
  selenium-hub:
    image: ghcr.io/${REPO_OWNER}/${REPO_NAME}-hub:${MAGE_TAG}
    container_name: selenium-hub
    ports:
      - "4444:4444"
    networks:
      - selenium-grid-network

  selenium-edge:
    image: ghcr.io/${REPO_OWNER}/${REPO_NAME}-edge:${MAGE_TAG}
    shm_size: 2g
    volumes:
      - /dev/shm:/dev/shm
      - $DOWNLOADS_FOLDER:/home/seluser/Downloads
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
    networks:
      - selenium-grid-network
    depends_on:
      - selenium-hub
    scale: 0

  selenium-chrome:
    image: ghcr.io/${REPO_OWNER}/${REPO_NAME}-chrome:${MAGE_TAG}
    shm_size: 2g
    volumes:
      - /dev/shm:/dev/shm
      - $DOWNLOADS_FOLDER:/home/seluser/Downloads
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
    networks:
      - selenium-grid-network
    depends_on:
      - selenium-hub
    scale: 0

  selenium-firefox:
    image: ghcr.io/${REPO_OWNER}/${REPO_NAME}-firefox:${MAGE_TAG}
    shm_size: 2g
    volumes:
      - /dev/shm:/dev/shm
      - $DOWNLOADS_FOLDER:/home/seluser/Downloads
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
    networks:
      - selenium-grid-network
    depends_on:
      - selenium-hub
    scale: 0


networks:
  selenium-grid-network:
    driver: bridge