ARG BASE_VERSION
FROM selenium/hub:${BASE_VERSION}

USER root

RUN apt-get update \
    && DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends tzdata \
    && rm -rf /var/lib/apt/lists/*

ENV TZ="Europe/Amsterdam"

USER seluser